### ISSUE TITLE
An Activity is not shared and with permission however the framework shows the wrong result. 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/Mobile-Security-Framework-MobSF#39]
An Activity was found to be shared with other apps on the device therefore leaving it accessible to any other application on the device. The presence of intent-filter indicates that the Activity is explicitly exported.

here are drozer result for the - om.yahoo.mobile.client.android.im 

 -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
dz> run app.activity.info -a com.yahoo.mobile.client.android.im
Package: com.yahoo.mobile.client.android.im
  com.yahoo.mobile.client.android.im.YahooMessenger
  com.yahoo.mobile.client.android.im.LoginScreenActivity
  com.yahoo.mobile.client.share.activity.LoginActivity
    Permission: com.yahoo.mobile.client.android.permissions.YAHOO_INTER_APP
  com.yahoo.mobile.client.share.activity.SignUpActivity
    Permission: com.yahoo.mobile.client.android.permissions.YAHOO_INTER_APP
  com.yahoo.mobile.client.android.im.SendToActivity
    Permission: com.yahoo.mobile.client.android.permissions.YAHOO_INTER_APP
    Target Activity: com.yahoo.mobile.client.android.im.BuddyListActivity
  com.yahoo.mobile.client.android.im.BrowserActivity
    Permission: com.yahoo.mobile.client.android.permissions.YAHOO_INTER_APP
  com.yahoo.mobile.client.android.im.ConversationActivity
  com.yahoo.mobile.client.android.im.SettingsActivity
    Permission: com.yahoo.mobile.client.android.permissions.YAHOO_INTER_APP
  com.yahoo.mobile.client.android.im.NearbyLocationActivity

![screen shot 2015-06-21 at 1 20 53 pm](https://cloud.githubusercontent.com/assets/6933052/8270901/62dd2b3c-1818-11e5-8a38-2c8a702f8550.png)

    Permission: com.yahoo.mobile.client.android.permissions.YAHOO_INTER_APP
  com.yahoo.mobile.client.android.im.LocationDetailsActivity
    Permission: com.yahoo.mobile.client.android.permissions.YAHOO_INTER_APP
  com.yahoo.mobile.client.android.im.AddLocationActivity
    Permission: com.yahoo.mobile.client.android.permissions.YAHOO_INTER_APP
  com.yahoo.mobile.client.android.im.TextDisplayPreference
    Permission: com.yahoo.mobile.client.android.permissions.YAHOO_INTER_APP
  com.yahoo.mobile.client.android.im.ContactViewActivity
    Permission: com.yahoo.mobile.client.android.permissions.YAHOO_INTER_APP
  com.yahoo.mobile.client.android.im.ContactEditActivity
    Permission: com.yahoo.mobile.client.android.permissions.YAHOO_INTER_APP
  com.yahoo.mobile.client.android.im.NewConversationActivity
    Permission: com.yahoo.mobile.client.android.permissions.YAHOO_INTER_APP
  com.yahoo.mobile.client.share.sync.account.AccountServiceSelectActivity
  com.yahoo.mobile.client.share.sync.account.AccountSetupActivity
  com.yahoo.mobile.client.share.sync.account.AccountResetPassword
  com.yahoo.mobile.client.share.sync.account.AccountSettingActivity

**Comment by bugwrangler** [comment]
This sounds like a regression issue, Activity which has permission are being displayed unnecessarily.

**Comment by ajinabraham** [comment]
Will be tracking this soon.

1 more thing to fix
for some APK, launcher activity is marked exported.

**Comment by bugwrangler** [comment]
aha exactly, good catch!

**Comment by ajinabraham** [comment]
Fixed MainActivity Exported issue. Will investigate the issue you reported.

**Comment by ajinabraham** [comment]
fixed

**Comment by fuomag9** [comment]
This is still not fixed, I got the same issue today (can't show activities due to privacy)
